export enum DSLayoutBackground {
    default = "default",
    defaultVariation1 = "default-variation1",
    defaultVariation2 = "default-variation2",
    defaultVariation3 = "default-variation3",
    background = "background",
    darkestBackground = "darkest-background",
    lightestBackground = "lightest-background",
    primary = "primary",
    primaryLighter = "primary-lighter",
    primaryDarker = "primary-darker",
    primaryHover = "primary-hover",
    secondary = "secondary",
    secondaryLighter = "secondary-lighter",
    secondaryDarker = "secondary-darker",
    accent = "accent",
    accentLighter = "accent-lighter",
    accentDarker = "accent-darker",
    success = "success",
    info = "info",
    critical = "critical",
    transparent = "transparent",
    white = "white",
    whiteVariation1 = "white-variation1",
    whiteVariation2 = "white-variation2",
    whiteVariation3 = "white-variation3",
    black = "black",
    blackVariation1 = "black-variation1",
    blackVariation2 = "black-variation2",
    blackVariation3 = "black-variation3",
}

export const backgroundClasses: Record<DSLayoutBackground, string> = {
    [DSLayoutBackground.default]: "ds-bg-default",
    [DSLayoutBackground.defaultVariation1]: "ds-bg-default-variation1",
    [DSLayoutBackground.defaultVariation2]: "ds-bg-default-variation2",
    [DSLayoutBackground.defaultVariation3]: "ds-bg-default-variation3",
    [DSLayoutBackground.background]: "ds-bg-background",
    [DSLayoutBackground.darkestBackground]: "ds-bg-darkest-background",
    [DSLayoutBackground.lightestBackground]: "ds-bg-lightest-background",
    [DSLayoutBackground.primary]: "ds-bg-primary",
    [DSLayoutBackground.primaryLighter]: "ds-bg-primary-lighter",
    [DSLayoutBackground.primaryDarker]: "ds-bg-primary-darker",
    [DSLayoutBackground.primaryHover]: "ds-bg-primary-hover",
    [DSLayoutBackground.secondary]: "ds-bg-secondary",
    [DSLayoutBackground.secondaryLighter]: "ds-bg-secondary-lighter",
    [DSLayoutBackground.secondaryDarker]: "ds-bg-secondary-darker",
    [DSLayoutBackground.accent]: "ds-bg-accent",
    [DSLayoutBackground.accentLighter]: "ds-bg-accent-lighter",
    [DSLayoutBackground.accentDarker]: "ds-bg-accent-darker",
    [DSLayoutBackground.success]: "ds-bg-success",
    [DSLayoutBackground.info]: "ds-bg-info",
    [DSLayoutBackground.critical]: "ds-bg-critical",
    [DSLayoutBackground.transparent]: "ds-bg-transparent",
    [DSLayoutBackground.white]: "ds-bg-white",
    [DSLayoutBackground.whiteVariation1]: "ds-bg-white-variation1",
    [DSLayoutBackground.whiteVariation2]: "ds-bg-white-variation2",
    [DSLayoutBackground.whiteVariation3]: "ds-bg-white-variation3",
    [DSLayoutBackground.black]: "ds-bg-black",
    [DSLayoutBackground.blackVariation1]: "ds-bg-black-variation1",
    [DSLayoutBackground.blackVariation2]: "ds-bg-black-variation2",
    [DSLayoutBackground.blackVariation3]: "ds-bg-black-variation3",
};

// CSS variable references for the same tokens, used when mixing with opacity.
export const backgroundColorVars: Partial<Record<DSLayoutBackground, string>> = {
    [DSLayoutBackground.default]: "var(--default-background)",
    [DSLayoutBackground.defaultVariation1]: "var(--default-background-variation1)",
    [DSLayoutBackground.defaultVariation2]: "var(--default-background-variation2)",
    [DSLayoutBackground.defaultVariation3]: "var(--default-background-variation3)",
    [DSLayoutBackground.background]: "var(--background)",
    [DSLayoutBackground.darkestBackground]: "var(--darkest-background)",
    [DSLayoutBackground.lightestBackground]: "var(--lightest-background)",
    [DSLayoutBackground.primary]: "var(--primary)",
    [DSLayoutBackground.primaryLighter]: "var(--primary-lighter)",
    [DSLayoutBackground.primaryDarker]: "var(--primary-darker)",
    [DSLayoutBackground.primaryHover]: "var(--primary-button-hover)",
    [DSLayoutBackground.secondary]: "var(--secondary)",
    [DSLayoutBackground.secondaryLighter]: "var(--secondary-lighter)",
    [DSLayoutBackground.secondaryDarker]: "var(--secondary-darker)",
    [DSLayoutBackground.accent]: "var(--accent)",
    [DSLayoutBackground.accentLighter]: "var(--accent-lighter)",
    [DSLayoutBackground.accentDarker]: "var(--accent-darker)",
    [DSLayoutBackground.success]: "var(--success)",
    [DSLayoutBackground.info]: "var(--info)",
    [DSLayoutBackground.critical]: "var(--critical)",
    [DSLayoutBackground.transparent]: "transparent",
    [DSLayoutBackground.white]: "var(--background-white)",
    [DSLayoutBackground.whiteVariation1]: "var(--background-white-variation-1)",
    [DSLayoutBackground.whiteVariation2]: "var(--background-white-variation-2)",
    [DSLayoutBackground.whiteVariation3]: "var(--background-white-variation-3)",
    [DSLayoutBackground.black]: "var(--background-black)",
    [DSLayoutBackground.blackVariation1]: "var(--background-black-variation1)",
    [DSLayoutBackground.blackVariation2]: "var(--background-black-variation2)",
    [DSLayoutBackground.blackVariation3]: "var(--background-black-variation3)",
};
